In [3]:
import numpy as np
print(np.__version__)

2.0.2


In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [13]:
np.ones([2, 2], dtype=int)

array([[1, 1],
       [1, 1]])

In [15]:
np.ones([3, 2], dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
X = np.arange(4, dtype=int)
X

array([0, 1, 2, 3])

In [20]:
np.ones_like(X)

array([1, 1, 1, 1])

In [22]:
X = np.array([[1,2,3], [4,5,6]], dtype=int)
X

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
np.ones([4, 4], dtype=int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [27]:
X = np.array([[2,3], [6,2]], dtype=int)
X

array([[2, 3],
       [6, 2]])

In [30]:
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

In [32]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.random.randint(10, size=3)

array([6, 7, 7])

In [38]:
np.random.randn(3, 3 ,3)

array([[[-2.7227543 , -0.3886327 ,  0.1927866 ],
        [-0.01989133,  1.55817715,  0.41332847],
        [ 0.52390818, -0.12085402, -1.57620595]],

       [[-0.76488849, -1.15565321, -0.65966044],
        [ 0.56398258,  2.24505343, -0.99368065],
        [ 1.4721946 , -1.0864649 , -0.90454559]],

       [[-1.30747455, -0.08643244,  0.2125653 ],
        [-0.8199112 ,  1.06332549, -0.47907573],
        [-1.41902811, -1.00917404,  1.11764178]]])

In [41]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [46]:
X = np.array([5, 2, 3], dtype=int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y))

[5 2 3] 4646691152
[5 2 3] 4646840048


In [48]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [54]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [59]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
Z = np.zeros((10, 10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [68]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[0]

np.str_('A')

In [70]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[-1]

np.str_('E')

In [73]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

In [75]:
X = np.array(['A', 'B', 'C', 'D', 'E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [77]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [ ]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[::2]

array(['A', 'C', 'E'], dtype='<U1')